---
title: Municipal Elections Archive
description: Archive of candidates and results for municipal elections in Waterloo Region

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock

collections_dir: collections
collections:
  municipalities:
    output: true
    permalink: /:year/:title/ # could also use :path or :name

defaults:
  -
    scope:
      path: ""
      type: "municipalities"
    values:
      layout: "default"

remote_theme: pmarsceill/just-the-docs

