---
title: Municipal Elections Archive
description: Archive of candidates and results for municipal elections in Waterloo Region

collections_dir: collections
collections:
  municipalities:
    output: true
    permalink: /:title/ # could also use :path or :name

defaults:
  -
    scope:
      path: ""
      type: "municipalities"
    values:
      layout: "default"

remote_theme: pmarsceill/just-the-docs

